var orderSummry='';
orderSummry +='<table cellpadding="4" cellspacing="0" border="0" width="300pt">'
orderSummry +='    <tr>'
orderSummry +='        <td width="30pt">'
orderSummry +='            Relish'
orderSummry +='        </td>'
orderSummry +='        <td colspan="4">'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr style="line-height:3px">'
orderSummry +='        <td colspan="5">'
orderSummry +='            -----------------------------------------------------'
orderSummry +='</td>'
orderSummry +='    </tr>'
orderSummry +='	<tr>'
orderSummry +='        <td>'
orderSummry +='            Date:'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            09-07-2013'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            Time:'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            13:02:05'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='    <tr>'
orderSummry +='        <td>'
orderSummry +='            Table&nbsp;No:'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            1'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            Server:'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            Anthony'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='    <tr>'
orderSummry +='        <td>'
orderSummry +='            Item'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            Qty'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr style="line-height:3px">'
orderSummry +='        <td colspan="5">'
orderSummry +='            ------------------------X----------------------------'
orderSummry +='</td>'
orderSummry +='    </tr>'
    orderSummry +='<tr>'
        orderSummry +='<td colspan="2">'
orderSummry +='            Relish Mojito'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            1'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr style="line-height:3px">'
orderSummry +='        <td colspan="5">'
orderSummry +='            ------------------------X----------------------------'
orderSummry +='</td>'
orderSummry +='    </tr>'
	 orderSummry +='<tr>'
orderSummry +='        <td colspan="2">'
orderSummry +='            Onion Rings'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            1'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr style="line-height:3px">'
orderSummry +='        <td colspan="5">'
orderSummry +='            ------------------------X----------------------------'
orderSummry +='</td>'
orderSummry +='    </tr>'
orderSummry +='	<tr>'
orderSummry +='        <td colspan="2">'
orderSummry +='            Wild Rocket Beef Burger'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            &nbsp;'
        orderSummry +='</td>'
orderSummry +='        <td>'
orderSummry +='            1'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr>'
orderSummry +='        <td >'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            Medium Rare'
orderSummry +='        </td>'
orderSummry +='		<td >'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr>'
orderSummry +='        <td >'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            Truffle Fries'
orderSummry +='        </td>'
orderSummry +='		<td >'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            1'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr>'
orderSummry +='        <td >'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
            orderSummry +='Add Cheese'
orderSummry +='        </td>'
orderSummry +='		<td >'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            1'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr style="line-height:3px">'
orderSummry +='        <td colspan="5">'
orderSummry +='            ------------------------X----------------------------'
orderSummry +='</td>'
orderSummry +='    </tr>'
orderSummry +='	<tr>'
orderSummry +='        <td colspan="2">'
orderSummry +='            Thai Basil Pesto Bee Tai Bak'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            1'
orderSummry +='        </td>'
orderSummry +='    </tr>'
	orderSummry +='<tr>'
orderSummry +='        <td >'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            Less Spicy'
orderSummry +='        </td>'
orderSummry +='		<td >'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='	<tr style="line-height:3px">'
orderSummry +='        <td colspan="5">'
orderSummry +='            ------------------------X----------------------------'
orderSummry +='</td>'
orderSummry +='    </tr>'
orderSummry +='	<tr>'
orderSummry +='        <td colspan="2">'
orderSummry +='            Panna Cotta'
orderSummry +='        </td>'
orderSummry +='        <td colspan="2">'
orderSummry +='            &nbsp;'
orderSummry +='        </td>'
orderSummry +='        <td>'
orderSummry +='            1'
orderSummry +='        </td>'
orderSummry +='    </tr>'
orderSummry +='</table>'

$( document ).ready(function() {
$("#printHtml").val(orderSummry);
});